context:
  name: tof
  version: "25.10.1"
  python_min: "3.11"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/tof-${{ version }}.tar.gz
  sha256: 95a4bf4a96b0a247e1ac4c44f168e7cd8e4d51f102eb2ab8f65a770806ca95f1

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=77
    - setuptools-scm >=8.0
    - pip
  run:
    - python >=${{ python_min }}
    - plopp
    - scipp
    - scipy
    - lazy-loader

tests:
  - python:
      imports:
        - tof
      python_version: ${{ python_min }}.*

about:
  summary: A simple tool to create time-of-flight chopper cascade diagrams
  license: BSD-3-Clause
  license_file: LICENSE
  repository: https://github.com/scipp/tof
  homepage: https://scipp.github.io/tof/

extra:
  recipe-maintainers:
    - MridulS
    - conda-forge/scipp
